name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      SolutionName: Mews.Fiscalization.Greece.sln
      TestProjectPath: Mews.Fiscalization.Greece.Tests/Mews.Fiscalization.Greece.Tests.csproj
      
    defaults:
      run:
        working-directory: src
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
